const popularBrands = [
  "Penti",
  "Watsons",
  "Stradivarius",
  "Columbia",
  "Puma",
  "Apple",
  "Xiaomi",
  "Birkenstock",
  "Adidas",
  "Lacoste",
  "Madame Coco",
  "Defacto",
  "Tchibo",
  "Network",
  "Kıgılı",
  "Mango",
  "English Home",
  "The North Face",
  "Samsung",
  "Mudo",
  "New Balance",
  "Oppo",
  "Arçelik",
  "Nike",
  "Avva",
  "Pull & Bear",
  "Mavi",
  "Farmasi",
  "Bosch",
  "Migros",
  "Vivense",
  "Bershka",
  "Beymen",
  "Lumberjack",
  "Derimod",
  "Huawei",
  "Monster Notebook",
  "DYSON",
  "Skechers",
  "Under Armour",
  "Koton",
  "Pierre Cardin",
  "Helly Hansen",
  "Karaca",
  "CAT",
  "Bluetooth Kulaklık",
  "Azerbaycan'dan Alışveriş",
  "Laptop",
  "iPhone 15 Plus",
  "Apple Watch",
  "Buzdolabı",
  "Öğrencilere Vergisiz Alışveriş",
  "Apple Watch Series 9",
  "Erkek Mont",
  "Kahve Makinesi",
  "Oyuncu Koltuğu",
  "Popüler Kategoriler",
  "Apple Airpods",
  "Markalar",
  "Erkek Sweatshirt",
  "iPhone",
  "Nike Air Max",
  "iPhone 15",
  "iPhone 15 Pro",
  "Çamaşır Makinesi",
  "Anneler Günü Hediyesi",
  "E-İhracat",
  "Termos",
  "Sınav Hazırlık ve Test Kitapları",
  "Kitap",
  "Elbise",
  "Kadın Bot",
  "Roman, Hikaye ve Edebiyat Kitapları",
  "Macbook",
  "Trendyol Arabic",
  "Samsung Cep Telefonu",
  "Robot Süpürge",
  "Soba & Isıtıcı",
  "iPhone 15 Pro Max",
  "Bulaşık Makinesi",
  "Öğrencilere Vergisiz Alışveriş",
  "Sırt Çantası",
  "Kadın Mont",
  "Televizyon",
  "Sneaker",
  "Popüler Aramalar",
  "Dyson Airwrap",
  "Trendyol Blog",
  "Trendyol English",
  "Trendyol Deutsch",
];

const populerSayfalar = [
  "Bluetooth Kulaklık",
  "Azerbaycan'dan Alışveriş",
  "Laptop",
  "iPhone 15 Plus",
  "Apple Watch",
  "Buzdolabı",
  "Öğrencilere Vergisiz Alışveriş",
  "Apple Watch Series 9",
  "Erkek Mont",
  "Kahve Makinesi",
  "Oyuncu Koltuğu",
  "Popüler Kategoriler",
  "Apple Airpods",
  "Markalar",
  "Erkek Sweatshirt",
  "iPhone",
  "Nike Air Max",
  "iPhone 15",
  "iPhone 15 Pro",
  "Çamaşır Makinesi",
  "Anneler Günü Hediyesi",
  "E-İhracat",
  "Termos",
  "Sınav Hazırlık ve Test Kitapları",
  "Kitap",
  "Elbise",
  "Kadın Bot",
  "Roman, Hikaye ve Edebiyat Kitapları",
  "Macbook",
  "Trendyol Arabic",
  "Samsung Cep Telefonu",
  "Robot Süpürge",
  "Soba & Isıtıcı",
  "iPhone 15 Pro Max",
  "Bulaşık Makinesi",
  "Öğrencilere Vergisiz Alışveriş",
  "Sırt Çantası",
  "Kadın Mont",
  "Televizyon",
  "Sneaker",
  "Popüler Aramalar",
  "Dyson Airwrap",
  "Trendyol Blog",
  "Trendyol English",
  "Trendyol Deutsch",
];

export { popularBrands, populerSayfalar };
